In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
print(mnist)

<module 'keras.api.datasets.mnist' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/api/datasets/mnist/__init__.py'>


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2024-08-26 18:16:31.898409: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2024-08-26 18:16:31.898444: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2024-08-26 18:16:31.898450: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2024-08-26 18:16:31.898674: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-08-26 18:16:31.898697: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorF

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3047449 , -0.24335003, -0.05252098, -0.37497723,  0.92651254,
        -0.09901184,  0.3579805 ,  0.11872149,  0.40524578, -0.8222104 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.06651741, 0.0707292 , 0.08560019, 0.062006  , 0.22785763,
        0.08171166, 0.12904859, 0.10158847, 0.13529456, 0.03964632]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.5045586

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-08-26 18:18:24.623088: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8571 - loss: 0.4835
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9580 - loss: 0.1452
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9675 - loss: 0.1050
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9733 - loss: 0.0847
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9776 - loss: 0.0721


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9781 - loss: 0.0758


[0.07583843916654587, 0.9781000018119812]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.28592442e-08, 1.56330614e-07, 7.47643708e-06, 2.88616982e-04,
        8.02852229e-12, 1.43228954e-06, 1.52869050e-13, 9.99701083e-01,
        1.90517525e-07, 9.37989057e-07],
       [2.07831685e-09, 1.05144154e-05, 9.99987960e-01, 2.37510221e-07,
        5.25128002e-18, 4.17677086e-07, 1.25774173e-08, 1.90666507e-13,
        8.59446118e-07, 4.83891288e-15],
       [1.89032932e-07, 9.97356653e-01, 1.24719634e-04, 3.03528736e-06,
        5.72406570e-05, 1.17266482e-05, 2.28959016e-05, 5.19802968e-04,
        1.90193148e-03, 1.72914463e-06],
       [9.99974728e-01, 8.11934797e-10, 1.52980483e-05, 1.41437141e-07,
        7.46980033e-10, 1.25196186e-06, 5.74624164e-06, 1.11673856e-07,
        1.86118481e-08, 2.61263926e-06],
       [4.24193713e-05, 4.89724279e-08, 3.82145299e-05, 1.06509788e-07,
        9.98221934e-01, 5.90729542e-07, 2.58125897e-06, 4.93362677e-05,
        1.01465446e-06, 1.64367456e-03]], dtype=float32)>